global using Microsoft.AspNetCore.OData;
global using Microsoft.EntityFrameworkCore;
global using Musicfy.API.Entities.Data;
global using Musicfy.API.Entities.DataModel;
global using Serilog.Sinks.SystemConsole.Themes;
global using Serilog;
global using Microsoft.OData.Edm;
global using Microsoft.OData.ModelBuilder;
global using System.ComponentModel.DataAnnotations;